site_name: CORE â€” Community Obsidian Resource Exchange
site_description: Open, community-driven learning resources for computer science, cybersecurity, cloud, and AI
site_author: CORE Community

docs_dir: Docs
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  
  - Roadmap: roadmap.md

  - Beginner:
      - Computer Science:
          - What is a Computer?: ../notes/beginner/cs/what-is-a-computer.md
      - Linux: []
      - Networking: []
      - Git: []

  - Intermediate:
      - Web: []
      - Databases: []
      - Cloud: []
      - Security: []

  - Advanced:
      - Red Teaming: []
      - Cloud Security: []
      - Malware: []
      - AI: []

  - Labs: ../notes/labs/index.md
  - Cheatsheets: ..notes/cheatsheets/index.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
